//LOCAL HOST
###
GET http://localhost:3000/contacts


###
POST  http://localhost:3000/contacts
Content-Type: application/json

 {
        "firstName": "tatenda",
        "lastName": "nyamuda",
        "email": "tatenda@gmail.com",
        "favoriteColor": "orange",
        "birthday": "12/05/1900"

    }



###
GET http://localhost:3000/contacts/632614d52c2da193fe2b454b


###
GET http://localhost:3000/contacts/632614b62c2da193fe2b38e4

###
GET http://localhost:3000/contacts/6326149b2c2da193fe2b2dcb

###
PUT http://localhost:3000/contacts/632b46ee7f02525f5970c1db
Content-Type: application/json

 {
        "favoriteColor": "blue"

    }

###
DELETE http://localhost:3000/contacts/632b46ee7f02525f5970c1db



//PRODUCTION DEPLOY
###
GET https://cse341-cut4.onrender.com/contacts

###
POST https://cse341-cut4.onrender.com/contacts
Content-Type: application/json

 {
        "firstName": "tatenda",
        "lastName": "nyamuda",
        "email": "tatenda@gmail.com",
        "favoriteColor": "orange",
        "birthday": "12/05/1900"

    }

###
GET https://cse341-cut4.onrender.com/contacts/6326149b2c2da193fe2b2dcb

###
GET https://cse341-cut4.onrender.com/contacts/632614d52c2da193fe2b454b

###
PUT https://cse341-cut4.onrender.com/contacts/632b4786b55c240f98b16eac
Content-Type: application/json

 {
        "favoriteColor": "yellow"

    }

###
DELETE https://cse341-cut4.onrender.com/contacts/632b4786b55c240f98b16eac






